// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCSUeGgpC9ahaRND-tPzJbmSH0qQ3DLUw',
    appId: '1:306404517247:web:d626c56058b6149b90664a',
    messagingSenderId: '306404517247',
    projectId: 'todoapp-d37c5',
    authDomain: 'todoapp-d37c5.firebaseapp.com',
    storageBucket: 'todoapp-d37c5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDeF2DivA4tFJaBZ9NeZlz8BYiIivsU-tw',
    appId: '1:306404517247:android:0bde82588814cb5090664a',
    messagingSenderId: '306404517247',
    projectId: 'todoapp-d37c5',
    storageBucket: 'todoapp-d37c5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8eWsQELNpOz3Ol5JgxhD-HSQrKhniRSE',
    appId: '1:306404517247:ios:80b289ce4c30eebe90664a',
    messagingSenderId: '306404517247',
    projectId: 'todoapp-d37c5',
    storageBucket: 'todoapp-d37c5.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8eWsQELNpOz3Ol5JgxhD-HSQrKhniRSE',
    appId: '1:306404517247:ios:80b289ce4c30eebe90664a',
    messagingSenderId: '306404517247',
    projectId: 'todoapp-d37c5',
    storageBucket: 'todoapp-d37c5.firebasestorage.app',
    iosBundleId: 'com.example.toDoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCSUeGgpC9ahaRND-tPzJbmSH0qQ3DLUw',
    appId: '1:306404517247:web:a44a49268cac9d1890664a',
    messagingSenderId: '306404517247',
    projectId: 'todoapp-d37c5',
    authDomain: 'todoapp-d37c5.firebaseapp.com',
    storageBucket: 'todoapp-d37c5.firebasestorage.app',
  );
}
